apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: backend.prod.goal.tracker:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_PASSWORD
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: DB_URL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: ADMIN_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8000       
      targetPort: 8000