apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD:
  MYSQL_DATABASE:
  MYSQL_USER:
  MYSQL_PASSWORD:
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: prod
type: Opaque
stringData:
  DB_URL: jdbc:mysql://mysql.prod.svc.cluster.local/springboot_prod?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  ADMIN_PASSWORD: