apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-microservice
  namespace: prod
  labels:
    app: graph-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graph-microservice
  template:
    metadata:
      labels:
        app: graph-microservice
    spec:
      containers:
        - name: graph-microservice
          image: graph-microservice.prod.goal.tracker:0.0.1
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: BACKEND_URL
              value: http://backend-service.prod.svc.cluster.local:8000/
---
apiVersion: v1
kind: Service
metadata:
  name: graph-service
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: graph-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
