apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-frontend
  namespace: prod
  labels:
    app: flask-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-frontend
  template:
    metadata:
      labels:
        app: flask-frontend
    spec:
      containers:
        - name: flask-frontend
          image: flask-frontend.prod.goal.tracker:0.0.1  
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          env:
            - name: FLASK_RUN_HOST
              value: 0.0.0.0
            - name: BACKEND_URL
              value: http://backend-service.prod.svc.cluster.local:8000/
---
apiVersion: v1
kind: Service
metadata:
  name: flask-frontend
  namespace: prod
spec:
  type: ClusterIP
  selector:
    app: flask-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
